SELECT 
    BOOK_NAME,
    BOOK_AUTHOR, 
    BOOK_TYPE, 
    BOOK_PRICE,
    BOOK_AVAILLABLE, 
FROM 
    INFORMATION_BOOK_STORE_SCHEMA
WHERE 
    TABLE_SCHEMA = DATABASE() 
    AND TABLE_NAME = 'books';
